### PR TITLE
Fix a few window hints (proposed solution for #1316)

### PR DESCRIPTION
**Pull request by devernay**
A window without a frame is usually a popup
A window that always stays on top is usually a tool

### CODE REVIEW

**Comment by z3ntu** [comment]
rip github

**Comment by z3ntu** [comment]
Well I can't get the normal version to compile on Arch Linux, so I hope the next release includes this!

**Comment by olear** [comment]
I will test in i3 after work.

**Comment by olear** [comment]
Works perfectly :+1:

**Comment by olear** [comment]
This actually seems to break normal window managers, in KDE I can't use the mouse to select nodes with alt+tab anymore, the window just closes if I click on something with the mouse..

**Comment by olear** [comment]
Setting NodeCreationDialog to Qt::Tool fixes the mouse issue, but then textEdit don't get focus ...

**Comment by olear** [comment]
The only way I found to force focus when using Qt::Tool is to add QApplication::setActiveWindow(this) in the dialog construction and QApplication::setActiveWindow(parentWidget()) on delete. But now if I click outside the dialog it won't close, only esc or selecting a node will close the dialog.

**Pull request merged**
