### PR TITLE
Added return statement enable/disable via parser settings

### PR DESCRIPTION
**Pull request by ArashPartow**
- Added return statement enable/disable via parser settings
- Added exprtk_disable_return_statement macro for disabling return statements and associated exceptions at the source code level.

### CODE REVIEW

**Comment by MrKepzie** [comment]
@ArashPartow Currently we wrap the last statement of the expression with a "return" statement so that an expression can be used to return a string in a similar way that a scalar is returned, instead of explicitly requesting the user to type "return" for string-based expressions.

It would be very useful if the last node in output could be a string, even if the type of the expression object is e.g a double

**Comment by ArashPartow** [comment]
@MrKepzie Changing the code to implicitly allow returning a string value from an expression would still require the expression be queried after evaluation as the the type returned - because there could be situations where it's not possible to determine the type until the expression has been evaluated, eg:

```
if (x < y)
 1234;
else
'abc';
```

That being said, how about the following changes to **handleExprTkReturn**:

```
KnobHelper::ExpressionReturnValueTypeEnum
handleExprTkReturn(exprtk_expression_t& expressionObject,
                   double* retValueIsScalar,
                   string* retValueIsString,
                   string* error)
{
    const exprtk_scalar_t result    = expressionObject.value();
    const std::size_t results_count = results.count();

    if (results_count == 0) {
        *retValueIsScalar = result;
        return KnobHelper::eExpressionReturnValueTypeScalar;
    }
    else if (results_count != 1) {
        stringstream ss;
        ss << "Multiple return values not allowed.";
        *error = ss.str();
        return KnobHelper::eExpressionReturnValueTypeError;
    }

    typedef exprtk::results_context<exprtk_scalar_t> results_context_t;
    typedef typename results_context_t::type_store_t type_t;
    typedef typename type_t::scalar_view scalar_t;
    typedef typename type_t::string_view string_t;

    type_t t = expressionObject.results()[0];

    switch (t.type) {
    case type_t::e_scalar:
        (*retValueIsScalar) = scalar_t(t)();
        return KnobHelper::eExpressionReturnValueTypeScalar;

    case type_t::e_string:
        string_t str(t);
        (*retValueIsString).assign(str.begin(),str.end());
        return KnobHelper::eExpressionReturnValueTypeString;

    case type_t::e_vector:
    case type_t::e_unknown:
        stringstream ss;
        ss << "The expression must either return a scalar or string value depending on the parameter type";
        *error = ss.str();

        return KnobHelper::eExpressionReturnValueTypeError;
    }
}

```

**Comment by MrKepzie** [comment]
I understand and I did not go through the whole exprtk code to figure out what would be needed in order to make this work.
For now in Natron it is a bit dodgy to enable this to work, see [here](https://github.com/MrKepzie/Natron/blob/master/Engine/ExprTk.cpp#L1353):

Imagine the following expression:

    str(frame, 'f', 2)

In output the user wants a string representation of the current frame with the **str** function that I added to the the functions of the symbol table.

In Natron, the code explicitly declares a variable and return it:

    var NatronExprtkExpressionResult:= <USER_EXPRESSION>;
    return [NatronExprtkExpressionResult]

While this works OK if the user's expression has a single node on the last line, such as the one above, this does not work well if the line is something like:

    var condition := ... /*some value*/;
    condition ? str(frame, 'f', 2) : str(frame / 2, 'f', 2)

Simply because we would have to do complex parsing to obtain the final expression:

    var condition := ... /*some value*/;
    condition ? var NatronExprtkExpressionResult := str(frame, 'f', 2); : var NatronExprtkExpressionResult := str(frame / 2, 'f', 2);
    return [NatronExprtkExpressionResult]

So for now one limitation of the ExprTK based expressions in Natron is that the last line contains a simple expression with the output variable

**Comment by ArashPartow** [comment]
I think I can extended the sub-expression operator to properly handle the last sub-expression type properly and not just assume scalars. As a result you could transform your expressions as follows:

```
return
[~{
var condition1 := ... /*some value*/;
var condition2 := ... /*some value*/;
condition1 or condition2 ? str(frame, 'f', 2) : str(frame / 2, 'f', 2)
}]
```

That way you can take any expression and prepend "return [~{"  and append "}]" and it will always return one value, which could be either scalar, string or vector.

Would this be helpful?

**Comment by MrKepzie** [comment]
That would be great, it would then truly remain for the user the same as what's in the spec of exprtk. 
Regarding the proposed changes, I will incorporate it, it is more readable than the original version

**Comment by ArashPartow** [comment]
ok sounds good, I'll look into doing that. But note that it might take a few days.

**Pull request closed without merging**
