### PR TITLE
Fixed problem related to case-sensitivity of locally defined variables

### PR DESCRIPTION
**Pull request by ArashPartow**
- Fixed problem related to case-sensitivity of locally defined variables
- Fixed problem related to compilation with latest version of clang (version 5.0.0 trunk 303036)
- Minor code cleanup

### CODE REVIEW

**Comment by MrKepzie** [comment]
Thanks

**Comment by ArashPartow** [comment]
Were you able to resolve the build error? I don't think it's related to ExprTk.

**Comment by MrKepzie** [comment]
The build errors on Travis are due to OpenMP clause that were added recently that are not compatible with gcc 4.8.4.

**Comment by ArashPartow** [comment]
Aah ok. cool.

**Pull request merged**
